language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0

env:
  - PHPUNIT_VERSION="@stable"

matrix:
  include:
    - php: 5.6
      env: PHPUNIT_VERSION="4.0.*"
    - php: 5.6
      env: PHPUNIT_VERSION="4.1.*"
    - php: 5.6
      env: PHPUNIT_VERSION="4.2.*"
    - php: 5.6
      env: PHPUNIT_VERSION="4.3.*"
    - php: 5.6
      env: PHPUNIT_VERSION="4.4.*"
    - php: 5.6
      env: PHPUNIT_VERSION="4.5.*"
    - php: 5.6
      env: PHPUNIT_VERSION="4.6.*"
    - php: 5.6
      env: PHPUNIT_VERSION="4.8.*@dev"
    - php: 5.6
      env: PHPUNIT_VERSION="5.0.*@dev"


before_script:
    - composer install --prefer-dist
    - composer require phpunit/phpunit:${PHPUNIT_VERSION} -n --prefer-source
    - mkdir -p build/logs

script:
    - bin/phpunit --coverage-clover build/logs/clover.cov

after_script:
    - bin/ocular code-coverage:upload --format=php-clover build/logs/clover.cov
